import useProjectDetails from "./hook";
import TechListView from "../tech-listview";
import ColorPaletteListView from "../colorpalette-listview";
import NoteCard from "../../../../components/NoteCard";

function ProjectDetails() {
  const { builtWith,reactSpecificPackages,otherTechnologiesUsed,colorPalette } = useProjectDetails();
  return (
    <section className="w-full min-h-screen px-12 py-8 flex flex-col gap-4">
      <h1 className="w-full justify-center flex my-4"> Project Details </h1>
      <p> I would like to clarify that this project is for educational purposes only, the objective of this project is to study how social media applications work under the hood. why i specifically chose to study social media application architechture is because of how much network traffic they undergo every single day, the goal is to simulate how a systems design architect would design a social media app that scales and takes the full brunt of millions of users per day and millions of requests per day. </p>
      <NoteCard>
        <p className="text-white"> 30% of the code written was probably AI generated, however I reached that metric is up to interpretation <i className="text-gray-400">(with most of it just indentation fixes, style adjustments, code cleanups such as naming conventions and semantics and summarizing the error generated by the terminal)</i> so please take it with a grain of salt.  halfway through the project I will try experimenting on prompting techniques with AI as i am still working on financing my own self-hosted LLM <i className="text-gray-400">(I can't afford a monthly subscription)</i> that will hopefully "speed up" my workflow. while AI does have noticable benefits,I try not to commit fully to that route because in the end it is my responsibility to maintain the code i write and for now, AI still has its "gimmicks" but at the end of the day, what matters more is the architechture and less of the cleanliness of the code itself.</p>
      </NoteCard>
            <div className="flex flex-1 flex-col gap-4">
                <h1>Tech Stack</h1>
                <h2> built with </h2>
                <TechListView items={builtWith} />
                <h2> react specific packages </h2>
                <TechListView items={reactSpecificPackages} />
                <h2> other technologies used </h2>
                <TechListView items={otherTechnologiesUsed} />
            </div>

            <div className="flex flex-1 flex-col gap-4">
                <h1>Styles</h1>
                <h2> font-family </h2>
                <p> 'JetBrains Mono'</p>
                <h2> color palette </h2>
                <ColorPaletteListView items={colorPalette}/>
            </div>
    </section>
    
  );
}



export default ProjectDetails;