 spring.config.import=optional:file:.env[.properties]

logging.level.org.springframework.boot.context.config=DEBUG
logging.level.root=INFO
logging.level.com.zerofuku.socialmediaclone=DEBUG
logging.level.org.springframework.security=DEBUG
logging.file.name=logs/app.log
logging.logback.rollingpolicy.clean-history-on-start=true

spring.application.name=SocialMediaClone
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret.key=${JWT_SECRET}
jwt.secret.expiration=${JWT_EXPIRATION}
security.config.allowed.urls=${SECURITY_CONFIG_ALLOWED_URLS}
security.config.allowed.methods=${SECURITY_CONFIG_ALLOWED_METHODS}
security.config.allowed.headers=${SECURITY_CONFIG_ALLOWED_HEADERS}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true